kernel_version: 4.19.95-35

cluster_name: dev-k8s
cluster_lb: 1.1.1.1
cluster_lb_port: 8888
cluster_network_type: flannel

system_reserved_cpu: 500m
system_reserved_memory: 200m

k8s_version: v1.24.0
kube_packages:
  "v1.24.0":
    - kubelet-1.24.0-0
    - kubectl-1.24.0-0
    - kubeadm-1.24.0-0

# 已经提前通过ansible安装, 不写入playbook
kube_rpm_packages:
  "v1.24.0":
    - kubelet-1.24.0-0.x86_64.rpm
    - kubectl-1.24.0-0.x86_64.rpm
    - kubeadm-1.24.0-0.x86_64.rpm
    - kubernetes-cni-1.2.0-0.x86_64.rpm
    - cri-tools-1.19.0-0.x86_64.rpm

container_runtime: containerd # docker
docker_version: docker-ce-20.10.10-3.el7
containerd_version: 1.4.12-3.1.el7
