- name: Mkdir docker
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - /data0/kubelet
    - /data0/log/kube
    - /data0/log/apiserver
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /etc/docker/

- name: Copy kubelet logrotate script
  copy:
    src: clean-kubelet-log.sh
    dest: /etc/cron.daily/clean-kubelet-log.sh
    mode: 0755
    owner: root
    group: root


# TODO GPU machine install nvidia-docker
- name: Install kubelet/kubectl/kubeadm/docker
  yum:
    name: "{{ kube_packages[k8s_version] }}"
    state: present
    disable_plugin: fastestmirror
    update_cache: yes

- name: Docker config daemon.json
  template:
    src: docker-daemon.j2
    dest: /etc/docker/daemon.json
    trim_blocks: yes
    lstrip_blocks: yes

- name: Restart docker
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: 
    - docker
    # - kubelet

# - name: Check kubelet running
#   shell: systemctl is-active kubelet
#   register: kubelet_active_result
#   retries: 6
#   delay: 5
#   until: kubelet_active_result.stdout == 'active'

- name: Check docker running
  shell: systemctl is-active docker
  register: docker_active_result
  retries: 6
  delay: 5
  until: docker_active_result.stdout == 'active'

- name: Set cluster name
  copy:
    dest: /root/.kube/cluster
    content: |-
      {"cluster_name":"{{ cluster_name }}"}