- name: Check inventory node groups
  fail:
    msg: master, node, etcd required in host inventory file
  when: not ('etcd' in groups and 'master' in groups and 'node' in groups)
  delegate_to: localhost
  become: no
  run_once: yes

- name: Check hostname
  fail:
    msg: |
      check hostname please, if correct flush gather cache with --flush-cache
  when: ansible_facts.hostname != inventory_hostname_short

- name: Swapoff
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0
