env: dev
insecure_registries:
  - harbor.net
kube_image_repo: "registry.aliyuncs.com/google_containers"

docker_log_opts_max_file: 5

kernel_version: 4.19.95-35

cluster_name: dev-k8s
cluster_lb: 1.1.1.1
cluster_lb_port: 8888
cluster_network_type: flannel
system_reserved_cpu: 500m
system_reserved_memory: 200m
k8s_version: v1.24.0
kube_packages:
  "v1.24.0":
    - kubelet-1.24.0-0
    - kubectl-1.24.0-0
    - kubeadm-1.24.0-0
# 已经提前通过ansible安装, 不写入playbook
kube_rpm_packages:
  "v1.24.0":
    - kubelet-1.24.0-0.x86_64.rpm
    - kubectl-1.24.0-0.x86_64.rpm
    - kubeadm-1.24.0-0.x86_64.rpm
    - kubernetes-cni-1.2.0-0.x86_64.rpm
    - cri-tools-1.19.0-0.x86_64.rpm
etcd_count: 3
master_count: 1
container_runtime: containerd # docker
docker_version: docker-ce-20.10.10-3.el7
containerd_version: 1.4.12-3.1.el7


# note: etcd assets download, https://github.com/etcd-io/etcd/releases?page=7
https: yes
etcd_cert_dir: /etc/etcd/certs
etcdctl_env:
  ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
  ETCDCTL_CERT: "{{ etcd_cert_dir }}/server.pem"
  ETCDCTL_KEY: "{{ etcd_cert_dir }}/server-key.pem"
etcd_version_dict:
  v1.24.0: v3.5.16
# k8s version define etcd version
etcd_version: "{{ etcd_version_dict[k8s_version] }}"
etcd_tar_checksum:
  v3.4.7: 6a1b6443959f1ae0f2a883f678fef6c9afaecf1a
  v3.5.16: b4bf00b4adae87edba5a2aa3d7f2bb94deaed95a
etcd_data_dir: /data0/etcd-cluster
etcd_listen_port: 2379
etcd_listen_peer_port: 2380
etcd_service_name: etcd
