- name: Deploy rc scripts
  copy:
    src: "{{ item }}"
    dest: "/etc/rc.d/rc.sre/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - set-conntrack.sh
    - set-nice.sh
    - set-cgroupv2.sh

- name: Deploy rc.local
  copy:
    src: "rc.local"
    dest: "/etc/rc.d/rc.local"
    mode: "0755"
    owner: root
    group: root
