# rc
- name: Deploy rc scripts
  copy:
    src: "{{ item }}"
    dest: "/etc/rc.d/rc.sre/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - set-conntrack.sh
    - set-nice.sh
    # - set-cgroupv2.sh

- name: Deploy rc.local
  copy:
    src: "rc.local"
    dest: "/etc/rc.d/rc.local"
    mode: "0755"
    owner: root
    group: root

# sysctl
- name: Copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644
    owner: root
    group: root
    checksum: 7c8f79e08cba887996772baf2a77f6886968f19e

- name: Sysctl take effect
  shell: sysctl -p

# other
- name: Add sudoers for dev user
  copy:
    src: dev-sudoers
    dest: /etc/sudoers.d/dev-sudoers
    mode: 0644
    owner: root
    group: root

- name: Copy kubelet logrotate script
  copy:
    src: clean-kubelet-log.sh
    dest: /etc/cron.daily/clean-kubelet-log.sh
    mode: 0755
    owner: root
    group: root

- name: Adjust syslog logrotate
  copy:
    src: syslog
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644
    checksum: 434fdb792ed12e6d18cc344dae798ed06a1dc784