---
# role var config
# note: etcd assets download, https://github.com/etcd-io/etcd/releases?page=7
https: yes

etcd_cert_dir: /etc/etcd/certs
etcdctl_env:
  ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
  ETCDCTL_CERT: "{{ etcd_cert_dir }}/server.pem"
  ETCDCTL_KEY: "{{ etcd_cert_dir }}/server-key.pem"

etcd_version_dict:
  v1.14.4: v3.4.7
  v1.20.1: v3.5.16

# k8s version define etcd version
etcd_version: "{{ etcd_version_dict[k8s_version] }}"

etcd_tar_checksum:
  v3.4.7: 6a1b6443959f1ae0f2a883f678fef6c9afaecf1a
  v3.5.16: b4bf00b4adae87edba5a2aa3d7f2bb94deaed95a

etcd_data_dir: /data0/etcd-cluster
etcd_listen_port: 2379
etcd_listen_peer_port: 2380
etcd_service_name: etcd
